"""Add collaboration tables (Phase 1)

Revision ID: 9e26e194bc27
Revises: a1b2c3d4e5f6
Create Date: 2026-04-01 16:35:12.324054+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e26e194bc27'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clawbook_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clawbook_posts_created_at'), 'clawbook_posts', ['created_at'], unique=False)
    op.create_table('slack_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_rules', sa.Text(), nullable=False),
    sa.Column('summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('summary_time', sa.String(), nullable=False),
    sa.Column('high_mood_enabled', sa.Boolean(), nullable=False),
    sa.Column('high_mood_threshold', sa.Integer(), nullable=False),
    sa.Column('milestone_enabled', sa.Boolean(), nullable=False),
    sa.Column('include_full_content', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_configs_created_at'), 'slack_configs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_decision_paths',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('reasoning_steps', sa.JSON(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('final_decision', sa.JSON(), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('decision_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_paths_created_at'), 'ai_decision_paths', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_decision_paths_post_id'), 'ai_decision_paths', ['post_id'], unique=True)
    op.create_table('clawbook_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clawbook_comments_created_at'), 'clawbook_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_clawbook_comments_post_id'), 'clawbook_comments', ['post_id'], unique=False)
    op.create_table('clawbook_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clawbook_images_created_at'), 'clawbook_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_clawbook_images_post_id'), 'clawbook_images', ['post_id'], unique=False)
    op.create_table('clawbook_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clawbook_likes_created_at'), 'clawbook_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_clawbook_likes_post_id'), 'clawbook_likes', ['post_id'], unique=False)
    op.create_index('ix_clawbook_likes_post_user', 'clawbook_likes', ['post_id', 'user_id'], unique=True)
    op.create_table('collaboration_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_suggestion', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collaboration_comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_comments_created_at'), 'collaboration_comments', ['created_at'], unique=False)
    op.create_index('ix_collaboration_comments_post', 'collaboration_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_collaboration_comments_post_id'), 'collaboration_comments', ['post_id'], unique=False)
    op.create_index('ix_collaboration_comments_user', 'collaboration_comments', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_group', 'activity_logs', ['group_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_group_id'), 'activity_logs', ['group_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_index('ix_group_members', 'group_members', ['group_id', 'user_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('shared_with_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['clawbook_posts.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_created_at'), 'shares', ['created_at'], unique=False)
    op.create_index('ix_shares_group', 'shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_shares_group_id'), 'shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_shares_owner_id'), 'shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shares_post_id'), 'shares', ['post_id'], unique=False)
    op.create_index('ix_shares_post_owner', 'shares', ['post_id', 'owner_id'], unique=False)
    op.create_index('ix_shares_shared_with', 'shares', ['shared_with_id'], unique=False)
    op.create_index(op.f('ix_shares_shared_with_id'), 'shares', ['shared_with_id'], unique=False)
    # SQLite does not support ALTER COLUMN syntax - diagnose_history.created_at already NOT NULL from initial schema
    op.create_index(op.f('ix_diagnose_history_created_at'), 'diagnose_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnose_history_pod_name'), 'diagnose_history', ['pod_name'], unique=False)
    op.create_index('ix_diagnose_history_pod_namespace', 'diagnose_history', ['pod_name', 'namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diagnose_history_pod_namespace', table_name='diagnose_history')
    op.drop_index(op.f('ix_diagnose_history_pod_name'), table_name='diagnose_history')
    op.drop_index(op.f('ix_diagnose_history_created_at'), table_name='diagnose_history')
    # SQLite does not support ALTER COLUMN syntax - skipping
    op.drop_index(op.f('ix_shares_shared_with_id'), table_name='shares')
    op.drop_index('ix_shares_shared_with', table_name='shares')
    op.drop_index('ix_shares_post_owner', table_name='shares')
    op.drop_index(op.f('ix_shares_post_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_owner_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_group_id'), table_name='shares')
    op.drop_index('ix_shares_group', table_name='shares')
    op.drop_index(op.f('ix_shares_created_at'), table_name='shares')
    op.drop_table('shares')
    op.drop_index('ix_group_members', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_activity_logs_group_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index('ix_activity_group', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    op.drop_index('ix_collaboration_comments_user', table_name='collaboration_comments')
    op.drop_index(op.f('ix_collaboration_comments_post_id'), table_name='collaboration_comments')
    op.drop_index('ix_collaboration_comments_post', table_name='collaboration_comments')
    op.drop_index(op.f('ix_collaboration_comments_created_at'), table_name='collaboration_comments')
    op.drop_table('collaboration_comments')
    op.drop_index('ix_clawbook_likes_post_user', table_name='clawbook_likes')
    op.drop_index(op.f('ix_clawbook_likes_post_id'), table_name='clawbook_likes')
    op.drop_index(op.f('ix_clawbook_likes_created_at'), table_name='clawbook_likes')
    op.drop_table('clawbook_likes')
    op.drop_index(op.f('ix_clawbook_images_post_id'), table_name='clawbook_images')
    op.drop_index(op.f('ix_clawbook_images_created_at'), table_name='clawbook_images')
    op.drop_table('clawbook_images')
    op.drop_index(op.f('ix_clawbook_comments_post_id'), table_name='clawbook_comments')
    op.drop_index(op.f('ix_clawbook_comments_created_at'), table_name='clawbook_comments')
    op.drop_table('clawbook_comments')
    op.drop_index(op.f('ix_ai_decision_paths_post_id'), table_name='ai_decision_paths')
    op.drop_index(op.f('ix_ai_decision_paths_created_at'), table_name='ai_decision_paths')
    op.drop_table('ai_decision_paths')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slack_configs_created_at'), table_name='slack_configs')
    op.drop_table('slack_configs')
    op.drop_index(op.f('ix_clawbook_posts_created_at'), table_name='clawbook_posts')
    op.drop_table('clawbook_posts')
    # ### end Alembic commands ###
